# Generated by Django 4.0.2 on 2022-02-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collegs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('total_students', models.IntegerField(default=1000)),
                ('branches', models.IntegerField(default=6)),
                ('location', models.CharField(default='New Delhi', max_length=100)),
                ('university', models.CharField(default='IPU', max_length=200)),
            ],
        ),
    ]
