# Generated by Django 4.0.2 on 2022-02-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0003_alter_collegs_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegs',
            name='ranking',
            field=models.IntegerField(default=10),
        ),
    ]
