# Generated by Django 4.0.2 on 2022-02-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0004_collegs_ranking'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegs',
            name='certified',
            field=models.IntegerField(default=0),
        ),
    ]
