# Generated by Django 4.0.2 on 2022-02-14 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0003_society_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelationShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relationships.person')),
                ('society_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relationships.society')),
            ],
        ),
    ]
