# Generated by Django 4.0.2 on 2022-02-14 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0005_course_student_table_delete_relationship_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
        migrations.RemoveField(
            model_name='table',
            name='course_name',
        ),
        migrations.RemoveField(
            model_name='table',
            name='student_name',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Table',
        ),
    ]
