# Generated by Django 4.0.2 on 2022-02-16 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Student', max_length=50)),
                ('roll', models.CharField(default='100', max_length=10)),
                ('branch', models.CharField(default='cse', max_length=30)),
            ],
        ),
    ]
