# Generated by Django 4.0.2 on 2022-02-17 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_throttling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='name',
            field=models.CharField(default='Student<bound method Field.value_to_string of <django.db.models.fields.AutoField>>', max_length=50),
        ),
    ]
