# Generated by Django 4.0.2 on 2022-02-17 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_throttling', '0002_alter_students_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='name',
            field=models.CharField(default='Student', max_length=50),
        ),
    ]
