# Generated by Django 3.2.9 on 2022-02-14 07:15

import django.core.validators
from django.db import migrations, models
import validators.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, validators=[django.core.validators.MaxLengthValidator(50), django.core.validators.MinLengthValidator(3)])),
                ('age', models.IntegerField(validators=[validators.models.age_validation])),
            ],
        ),
    ]
